allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@next/eslint-plugin-next@16.2.12'
  - eslint-config-next@16.2.12
  - '@hookform/resolvers@5.5.7'
