allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true
patchedDependencies:
  pg@8.20.0: patches/pg@8.20.0.patch
